name: CI

on:
  pull_request:

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [
          '8.1',
          '8.2',
          '8.3'
        ]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl

      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer validate
        run: composer validate

      - name: Composer get cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        run: |
          composer --version
          if [[ ${{ matrix.php-version }} == '8.2' ]]; then
            composer update --prefer-stable --optimize-autoloader
          else
            composer install --optimize-autoloader
          fi

      - name: Warmup
        run: ./bin/spryker-toolkit container:dump

      - name: PHPStan checks
        run: composer stan

      - name: CodeStyle checks
        run: composer cs-check
